import Carousels from "@/components/Carousels";
import Cards_Fashion from "@/layouts/Cards";
import Feed_Back from "@/layouts/Feed_Back";
import Brands from "@/layouts/Brands";
import Head from "next/head";
import { Col, Row } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="home_page">
        <Carousels />
        <div className="w-95">
          <div className="discount mt-5 mb-5 p-5">
            <Row>
              <Col xs={12} sm={12} md={6} xl={4}>
                <div className="discount_item sm-mb-4">
                  <div className="item_content">
                    <div className="overlay"></div>
                    <div className="discount_info">
                      <h4>Get 10% Off</h4>
                      <span>on order above $10</span>
                    </div>
                  </div>
                </div>
              </Col>

              <Col xs={12} sm={12} md={6} xl={4}>
                <div className="discount_item">
                  <div className="item_content">
                    <div className="overlay"></div>
                    <div className="discount_info">
                      <h4>Get 12% Off</h4>
                      <span>on order above $12</span>
                    </div>
                  </div>
                </div>
              </Col>

              <Col xs={12} sm={12} md={6} xl={4}>
                <div className="discount_item">
                  <div className="item_content">
                    <div className="overlay"></div>
                    <div className="discount_info">
                      <h4>Get 14% Off</h4>
                      <span>on order above $14</span>
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </div>

          <section id="trend">
            <div className="fashion_trend mt-5 mb-5">
              <div className="trend_header mb-4">
                <h4>FASHION WOMENT TREND</h4>
              </div>
              <div className="trend_items">
                <Row>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/women/1.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/women/2.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/women/3.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/women/4.jpg"} />
                  </Col>
                </Row>
              </div>
            </div>

            <div className="fashion_trend mt-5 mb-5">
              <div className="trend_header mb-4">
                <h4>FASHION MEN TREND</h4>
              </div>
              <div className="trend_items">
                <Row>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/men/1.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/men/2.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/men/3.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/men/4.jpg"} />
                  </Col>
                </Row>
              </div>
            </div>

            <div className="fashion_trend mt-5 mb-5">
              <div className="trend_header mb-4">
                <h4>FASHION KID TREND</h4>
              </div>
              <div className="trend_items">
                <Row>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/kid/1.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/kid/2.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/kid/3.jpg"} />
                  </Col>
                  <Col xs={12} sm={6} md={6} xl={6} xxl={3}>
                    <Cards_Fashion url={"/img/product/kid/4.jpg"} />
                  </Col>
                </Row>
              </div>
            </div>
          </section>

          <section id="feedback">
            <div id="feedback_content">
              <div className="w-95">
                <Feed_Back />
              </div>
            </div>
          </section>

          <section id="brands">
            <Brands />
          </section>
        </div>
      </div>
    </>
  );
}
